### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by inscara** [enlivenapp/pubvana#7]
I've installed pubvana. The installation runs smoothly, but when I point the browser to: http://mysite.com/pubvana/ I got the error: "PHP Fatal error: Call to a member function num_rows() on boolean in /var/www/html/pubvana/pubvana/models/Blog_m.php on line 146"

Any ideas what's wrong?

**Comment by enlivenapp** [comment]
can you verify the database was installed correctly?
